[package]
name = "harmony_wasm"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.74"
js-sys = "0.3.55"
core = { package = "harmony_core", path = "../core" }